name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_name: NanokaLeaks
            setup_command: sudo apt-get update && sudo apt-get install -y gcc patchelf
            extra_flags: ""
          - os: windows-latest
            binary_name: NanokaLeaks.exe
            setup_command: echo "Windows runners already have MSVC compilers installed."
            extra_flags: "--windows-disable-console"

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OS Dependencies
        run: ${{ matrix.setup_command }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"

      - name: Install Project Dependencies
        run: uv sync

      - name: Compile with Nuitka
        run: >
          uv run nuitka
          --standalone
          --onefile
          --enable-plugin=pyqt6
          --assume-yes-for-downloads
          ${{ matrix.extra_flags }}
          -o ${{ matrix.binary_name }}
          main.py

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.binary_name }}
          generate_release_notes: true
