name: Build and Release Linux Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Linux Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc patchelf

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"

      - name: Install Project Dependencies
        run: uv sync

      - name: Compile with Nuitka
        run: uv run nuitka --standalone --onefile --enable-plugin=pyqt6 -o NanokaLeaks main.py

      - name: Create GitHub Release and Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          files: NanokaLeaks
          generate_release_notes: true
